name = "fuckweaomods"
compatibility_date = "2026-09-05"
pages_build_output_dir = "public"

[[d1_databases]]
binding = "DB"
database_name = "fuckweaomods"
database_id = "427f4feb-4ebf-48b2-af60-bc197b9fc567"
